### ISSUE TITLE
changing directory and building multiple things

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/pretext.py#1]
I couldn't implement https://github.com/StevenClontz/pretext.py/commit/5885c68caa37c0c630b6ffcc1ab70281b58bcbc5#diff-93f846607655c657cb3e36f5b94eebb5R49 because the build scripts `os.chdir` into `output` but this is never undone (so the second build tries to go one level deeper).

I think ideally finding a way to do this without changing the working directory of the script is best, but I had to do that myself to make `pretext view` work so I'm a hypocrite.

**Comment by oscarlevin** [comment]
Fixed at b144fc47e00883aaea18f9ab0851497f1f12cde7.  Still use os.chdir, but first convert all paths to absolute before passing them to the build functions.  Now when chdir-ing to the directory, it doesn't matter where you start.

This commit also adds input option.

Further, I went back to making format a click.argument.  I'm open to hearing an argument about the option to make this an option, though :)

**Comment by StevenClontz** [comment]
My thinking was, since the choices for format are a finite list, having them as options rather than arguments self-documents things in `pretext build --help`, including the whitelist of builds we currently support.

**Comment by oscarlevin** [comment]
I do like the self-documenting aspect.  But I like the error that gets thrown if you don't specify a format on pretext build.  Is there a way to specify that exactly one of a set of options must be selected?

**Comment by StevenClontz** [comment]
I believe https://click.palletsprojects.com/en/7.x/options/#feature-switches means you can set at most one of the options. I like having `pretext build` work without any configuration to build HTML by default. (When I'm authoring, I build HTML frequently, and sometimes build LaTeX/PDF at milestones. Eventually, the behavior when not specifying a format should be configurable.)

Reading more, we should also consider https://click.palletsprojects.com/en/7.x/options/#choice-options e.g. `pretext build --format=latex`.
