### ISSUE TITLE
release 0.0rc0

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/pretext.py#19]
I see 0.0rc0 has no open issues (except this one I'm opening). Assuming we're careful about handling issues, I can assume this means the project is ready to package and distribute for preview.

If you agree, let me know and close this and I'll get this done asap.

**Comment by oscarlevin** [comment]
I think we can be done by this afternoon, but right now I concerned about the stringparams.  I tried to add a publisher file option specifically, which I think is worth having as a separate option, even if it gets added to the dictionary of stringparams.  However, my testing with that has not been successful.  I have time this afternoon to try to sort that out.  But I have not yet tried other stringparams which concerns me.
