### ISSUE TITLE
Error-check format in build command

### ISSUE THREAD

**Issue by rbeezer** [StevenClontz/pretext.py#27]
I tried several different ways to get `latex-image` to work as a build format.  Totally silent failure.

Perhaps check that the `FORMAT` provided to the `build` command is legit and fail with a warning otherwise?

**Comment by StevenClontz** [comment]
@oscarlevin an elegant solution to this is to follow my proposal at #16, so in 74089fa I've re-implemented using options rather than an arbitrary argument for FORMAT.

If you're cool with this, close this issue; if not, feel free to revert 74089fa and discuss here or in #16.
