### ISSUE TITLE
HTML output directory structure

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/pretext.py#5]
Should we built HTML into a subfolder of output by default? E.g. do we want `project/output/index.html` and `project/output/book.tex`, or do we want `project/output/html/index.html` and `project/output/book.tex`? 

I think I prefer the former so it's easier to find non-HTML builds, but if the output folder was hosted online, it'd add an `html` to the URL that may not be ideal (e.g. the book is hosted at `localhost/html` rather than just `localhost`).

**Comment by oscarlevin** [comment]
When I build projects, I have an html output folder (sometimes its `docs` so github hosts in correctly) and a separate latex output directory.  We currently allow the user to specify the output directory on any `pretext build`, but I don't know what we would do with `pretext build all`.  I don't think we should enforce an html or latex subfolder for output, but perhaps we can make the defaults dependent on which target gets built.

**Comment by StevenClontz** [comment]
The output folder should be configurable, but we want reasonable defaults for authors who prefer convention over configuration.

The docs subfolder idea is very important for thinking about making publishing easy for authors. FWIW I've actually put `output` in the generated `.gitignore`, but that should be reconsidered based upon a recommended workflow for publishing on GitHub Pages.

**Comment by StevenClontz** [comment]
- output
    - html
    - latex

**Comment by oscarlevin** [comment]
Implemented at 9dc9cba.

**Comment by oscarlevin** [comment]
Refactored at 44b0081.  Code is cleaner and the base output directory can now be specified (will always have html and latex subdirectories).
